AssineJa/force-app/main/default/objects/Customer_Support__c/Customer_Support__c.object-meta.xml
<CustomObject>
    <label>Customer Support</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Customer Support Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers Support</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AssineJa/force-app/main/default/objects/Customer_Support__c/fields/CustuomerID__c.field-meta.xml
<CustomField>
    <fullName>CustuomerID__c</fullName>
    <label>CustuomerID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

AssineJa/force-app/main/default/classes/Handlers/HandlerTriggerCustomerSupport.cls
public with sharing class HandlerTriggerCustomerSupport {
    
    @future(callout=true)
    public static void processoCustomerSupportsAsync(Set<Id> idsSupports){

        List<Customer_Support__c> updateSupportList = new List<Customer_Support__c>();

        List<Customer_Support__c> supportWithData = SelectorCustomerSupport.getCustomerSupportsByIds(idsSupports);   
        
        for (Customer_Support__c data : supportWithData){

            String idNew =  SelectorCustomer.getCustomerByStripeID(data.CustuomerID__c);

            data.CustuomerID__c = idNew;

            updateSupportList.add(data);
        }

        update updateSupportList;

    }
}