AssineJa/force-app/main/default/objects/Customer_Support__c/Customer_Support__c.object-meta.xml
<CustomObject>
    <label>Customer Support</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Customer Support Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers Support</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AssineJa/force-app/main/default/objects/Customer_Support__c/fields/additional_info__c.field-meta.xml
<CustomField>
    <fullName>additional_info__c</fullName>
    <label>Dados Adicionais</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

AssineJa/force-app/main/default/objects/Customer_Support__c/fields/CustuomerID__c.field-meta.xml
<CustomField>
    <fullName>CustuomerID__c</fullName>
    <label>CustuomerID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

AssineJa/force-app/main/default/objects/Customer_Support__c/fields/prioridade__c.field-meta.xml
<CustomField>
    <fullName>prioridade__c</fullName>
    <label>prioridade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baixa</fullName>
            </value>
            <value>
                <fullName>Média</fullName>
            </value>
            <value>
                <fullName>Alta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

AssineJa/force-app/main/default/objects/Customer_Support__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aberto</fullName>
                <default>true</default>
                <label>Aberto</label>
            </value>
            <value>
                <fullName>Fechado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

AssineJa/force-app/main/default/classes/Services/ServiceCustomerSupport.cls
public with sharing class ServiceCustomerSupport {

    public static void createTicket(String customer, String description, String priority, String add_info){

        Customer_Support__c tsupport = new Customer_Support__c();

        tsupport.CustuomerID__c = customer;
        tsupport.Description__c = description;
        tsupport.prioridade__c = priority;
        tsupport.status__c = 'Aberto';
        tsupport.additional_info__c = add_info;

        insert tsupport;

    }

}