AssineJa/force-app/main/default/objects/Contract/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

AssineJa/force-app/main/default/objects/Contract/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

AssineJa/force-app/main/default/objects/Customer/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <label>email</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

AssineJa/force-app/main/default/objects/Customer/fields/Stripe_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Stripe Customer ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

AssineJa/force-app/main/default/objects/Product2/fields/Stripe_price_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_price_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Stripe price ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

AssineJa/force-app/main/default/classes/Selectors/SelectorContract.cls
public with sharing class SelectorContract {
    public static Contract getContractById(Id contractId) {
        return [SELECT Customer__r.Stripe_Customer_ID__c, 
                       Customer__r.email__c, 
                       Status,
                       Product__r.Stripe_price_ID__c FROM Contract WHERE Id = :contractId LIMIT 1];
    }

    public static List<Contract> getContractsByIds(Set<Id> contractIds) {
        return [
            SELECT Id, Status, 
                   Customer__r.Stripe_Customer_ID__c, 
                   Customer__r.email__c,
                   Customer__r.Name,
                   Customer__c,
                   Product__r.Stripe_price_ID__c                   
            FROM Contract 
            WHERE Id IN :contractIds
        ];
    }

    public static List<Contract> getAllContracts(){
        return [
            SELECT Id, 
                   Status, 
                   Name,
                   Customer__r.Stripe_Customer_ID__c, 
                   Customer__r.email__c,
                   Product__r.Stripe_price_ID__c,
                   Product__c,
                   Customer__c

            FROM Contract 
            LIMIT 10
        ]; 
    }
}