AssineJa/force-app/main/default/objects/Contract/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

AssineJa/force-app/main/default/objects/Contract/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

AssineJa/force-app/main/default/objects/Customer/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <label>email</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

AssineJa/force-app/main/default/objects/Customer/fields/Stripe_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Stripe Customer ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

AssineJa/force-app/main/default/objects/Product2/fields/Stripe_price_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_price_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Stripe price ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

AssineJa/force-app/main/default/classes/Handlers/HandleTriggerContractStripe.cls
public with sharing class HandleTriggerContractStripe {

    public static void processContracts(List<Contract> contracts) {
        
        Set<Id> contractIds = new Map<Id, Contract>(contracts).keySet();

        Map<String, String> mapCustomers = new Map<String, String>();

        Map<String, String> mapProducts = new Map<String, String>();
        
        List<Contract> contractsWithData = SelectorContract.getContractsByIds(contractIds);
        
        for (Contract contract : contractsWithData) {
            
            mapCustomers.put(contract.Customer__c, createStripeCustomer(contract)) ;

            createStripeSubscription(contract);
        }

        ServiceCustomer.updateStripeIdCustomer(mapCustomers);

    }

    public static String createStripeCustomer(Contract contract) {
        
        String id = '';
        
        if (contract.Customer__r != null) {
            id = ControllerStripe.createStripeCustomer(
                contract.Customer__r.name,
                contract.Customer__r.email__c
            );
        } 
        
        return id;
    }

    public static void createStripeSubscription(Contract contract) {

        if (contract.Customer__r.Stripe_Customer_ID__c != null && contract.Product__r.Stripe_price_ID__c != null) {

                ControllerStripe.createStripeSubscription(
                contract.Customer__r.Stripe_Customer_ID__c, 
                contract.Product__r.Stripe_price_ID__c

            );
        }     
    }
}