AssineJa/force-app/main/default/objects/Contract/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

AssineJa/force-app/main/default/objects/Contract/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

AssineJa/force-app/main/default/objects/Customer/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <label>email</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

AssineJa/force-app/main/default/objects/Product2/fields/Stripe_price_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_price_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Stripe price ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

AssineJa/force-app/main/default/classes/Services/ServiceContract.cls
public with sharing class ServiceContract {
    
    private InterfaceSelectorContract IScontract;
    private InterfaceControllerStripe IcontrollerStripe;

    public ServiceContract(InterfaceSelectorContract IScontract, InterfaceControllerStripe IcontrollerStripe){
        this.IScontract = IScontract;
        this.IcontrollerStripe = IcontrollerStripe;
    }

    public void processContractsAsync(Set<Id> contractIds) {

        Map<String, String> mapCustomers = new Map<String, String>();
        
        List<Contract> contractsWithData = IScontract.getContractsByIds(contractIds);
        
        for (Contract contract : contractsWithData) {

            String stripeId = createStripeCustomer(contract);
            if (String.isNotBlank(stripeId)) {
                mapCustomers.put(contract.Customer__c, stripeId);
            }
        }

        if (!mapCustomers.isEmpty()) {
            FactoryCustomer.getServiceCustomer().updateStripeIdCustomer(mapCustomers);
        }
    }

    public String createStripeCustomer(Contract contract) {
        
        String id = '';
        
        if (contract.Customer__r != null) {

            id = IcontrollerStripe.createStripeCustomer(                
                contract.Customer__r.Name,
                contract.Customer__r.email__c
            );

            System.debug('createStripeCustomer id: ' + id);

            if (id <> ''){
               createStripeSubscription(id, contract.Product__r.Stripe_price_ID__c);
            }
        } 
        
        return id;
    }

    public void createStripeSubscription(String customerId, String priceId) {

        if (customerId != null && priceId != null) {

            IcontrollerStripe.createStripeSubscription(
                    customerId, 
                    priceId

            );
        }     
    }

}