AssineJa/force-app/main/default/objects/Contract/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

AssineJa/force-app/main/default/objects/Contract/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

AssineJa/force-app/main/default/objects/Customer/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <label>email</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

AssineJa/force-app/main/default/objects/Customer/fields/Stripe_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Stripe Customer ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

AssineJa/force-app/main/default/objects/Product2/fields/Stripe_price_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_price_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Stripe price ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

AssineJa/force-app/main/default/classes/HandleTriggerContractStripe.cls
public with sharing class HandleTriggerContractStripe {
   
    public static void processContractes(List<Contract> contracts) {
        for (Contract contract : contracts) {
            if (contract.Status == 'Ativo') {
                createStripeCustomer(contract);
                createStripeSubscription(contract);
            }
        }
    }

    public static void createStripeCustomer(Contract contract) {
        ServiceStripe.createStripeCustomer(contract.Customer__r.Stripe_Customer_ID__c, contract.Customer__r.email__c);
    }

    public static void createStripeSubscription(Contract contract) {
        ServiceStripe.createStripeSubscription(contract.Customer__r.Stripe_Customer_ID__c, contract.Product__r.Stripe_price_ID__c);
    }
}