AssineJa/force-app/main/default/objects/Contract/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Customer</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

AssineJa/force-app/main/default/objects/Contract/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

AssineJa/force-app/main/default/objects/Contract/fields/status_adimplencia__c.field-meta.xml
<CustomField>
    <fullName>status_adimplencia__c</fullName>
    <label>status adimplencia</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sem definição</fullName>
                <default>true</default>
                <label>Sem definição</label>
            </value>
            <value>
                <fullName>Em_dia</fullName>
                <label>Em dia</label>
            </value>
            <value>
                <fullName>Atrasado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

AssineJa/force-app/main/default/objects/Customer/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <label>email</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

AssineJa/force-app/main/default/objects/Customer_Support__c/Customer_Support__c.object-meta.xml
<CustomObject>
    <label>Customer Support</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Customer Support Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customers Support</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

AssineJa/force-app/main/default/objects/Customer_Support__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <label>Customer</label>
    <referenceTo>Customer</referenceTo>
    <relationshipLabel>Customers Support</relationshipLabel>
    <relationshipName>Customers_Support</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

AssineJa/force-app/main/default/objects/Customer_Support__c/fields/CustuomerID__c.field-meta.xml
<CustomField>
    <fullName>CustuomerID__c</fullName>
    <label>CustuomerID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

AssineJa/force-app/main/default/objects/Customer_Support__c/fields/prioridade__c.field-meta.xml
<CustomField>
    <fullName>prioridade__c</fullName>
    <label>prioridade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Baixa</fullName>
            </value>
            <value>
                <fullName>Média</fullName>
            </value>
            <value>
                <fullName>Alta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

AssineJa/force-app/main/default/classes/Helpers/HelperTests.cls
public with sharing class HelperTests {

    public static Contract createTestContractComplete(){

        Product2 produto = createTestProduct();
        Customer cliente = createTestCustomer();

        return createTestContract(cliente.id, produto.id);
    }

    public static Contract createTestContract(Id customerId, Id productId) {
        Contract c = new Contract(
            
            Name = '001g7000009p9FxAAI',
            Status = 'Activated',
            Product__c = productId,
            Status_adimplencia__c = 'Não definido',
            Customer__c = customerId
        );

        insert c;

        return c;
    }

    public static Customer_Support__c createTestCustomerSupport(String customerId) {

        Customer_Support__c cs = new Customer_Support__c(
            CustuomerID__c = customerId,
            Description__c = 'Test description',
            prioridade__c = 'Alta'
        );

        insert cs;

        return cs;
    }

    public static Customer createTestCustomer() {
        Customer cust = new Customer(
            Name = 'Test Customer',
            Email__c = 'customer@example.com'
        );

        insert cust;

        return cust;
    }

    public static Product2 createTestProduct() {
        Product2 p = new Product2(
            Name = 'Test Product',
            IsActive = true
        );

        insert p;

        return p;

    }
}