AssineJa/force-app/main/default/objects/Customer/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <label>email</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

AssineJa/force-app/main/default/objects/Customer/fields/Stripe_Customer_ID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_Customer_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Stripe Customer ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

AssineJa/force-app/main/default/classes/Services/ServiceCustomer.cls
public with sharing class ServiceCustomer implements InterfaceCustomer{

    private InterfaceRepositoryMain irepository;

    public ServiceCustomer(InterfaceRepositoryMain irepository){
        this.irepository = irepository;
    }

   public void updateStripeIdCustomer(Map<String, String> customers) {

        List<Customer> listToUpdate = new List<Customer>();

        List<Customer> sfCustomers = [
            SELECT Id, email__c, Stripe_Customer_ID__c 
            FROM Customer 
            WHERE Id IN :customers.keySet()
        ];

        System.debug('sfCustomers' + sfCustomers);

        for (Customer sc : sfCustomers) {
            
            if (customers.containsKey(sc.Id)) { 
                sc.Stripe_Customer_ID__c = customers.get(sc.Id);            
                
                System.debug('email: ' + customers.get(sc.email__c));

                listToUpdate.add(sc);
            }
        }

        System.debug('customers.keySet(): ' + customers.keySet());

        if (!listToUpdate.isEmpty()) {
            irepository.updateCustomers(listToUpdate);
        }
    }
}